### ISSUE TITLE
Playing sound with a delay specified is ignored

### ISSUE THREAD

**Issue by bernarma** [missionpinball/mpf-gmc#12]
When playing a song on the latest version of the Godot library, when specifying a delay from MPF as per this example, the delay is ignored.

```
sound_player:
  mode_song1_started:
    song1:
      delay: 5s # this is ignored
      action: play
      start_at: (player_config.active_song_seconds if player_config.active_song == "song1" else 0)
      events_when_stopped: song_finished_playing
```

If I add the following bit of code to the GMCChannel.gd it works.
```
	if settings.get("delay"):
		await get_tree().create_timer(settings.get("delay")).timeout

```

Would you like me to raise a PR and submit for inclusion?
