### ISSUE TITLE
Playing sound with volume specified in config does not affect volume

### ISSUE THREAD

**Issue by bernarma** [missionpinball/mpf-gmc#13]
When playing a sound using the latest MPF (0.8 I think) and GMC, the volume has no effect on the volume that the sound plays. I have tried various values ranging from -80 to -1 and from 0.0 to 1.0 (and the default of 0.5) but none seem to have an effect.

```
sound_player:
  play_song1:
    song1:
      action: play
      volume: 0.5 # have tried other values such as 0.1, 1.0 (as per description)
```

My original use case is to "duck" the music that is playing in the background whilst in the bonus mode and then to increase the volume once the bonus mode has been disabled and the players next ball has started. Since I couldn't get ducking to work (even though the logs in Godot indicate that it has ducked for a specific duration at a specific attenuation level), it does not appear to work hence why I am trying to get just volume working to start with whilst I troubleshoot.

Hopefully that makes sense.
